image:
  file: .gitpod.Dockerfile

tasks:
  - name: setup-development-override-env
    command: ./gitpod/setup_env_override.sh


jetbrains:
    intellij:
        plugins:
            - org.intellij.scala
